In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('train.csv')

In [3]:
data.head()

,Id,Open_Date,City,City_Group,Type,P1,P2,P3,P4,P5,...,P29,P30,P31,P32,P33,P34,P35,P36,P37,revenue
0,0,7/17/1999,İstanbul,BigCities,IL,4,5.0,4.0,4.0,2,...,3.0,5,3,4,5,5,4,3,4,5653753
1,1,2/14/2008,Ankara,Big Cities,FC,4,5.0,4.0,4.0,1,...,3.0,0,0,0,0,0,0,0,0,6923131
2,2,3/9/2013,Diyarbakır,Other,IL,2,4.0,2.0,5.0,2,...,3.0,0,0,0,0,0,0,0,0,2055379
3,3,2/2/2012,Tokat,Other,IL,6,4.5,6.0,6.0,4,...,7.5,25,12,10,6,18,12,12,6,2675511
4,4,5/9/2009,Gaziantep,Other,IL,3,4.0,3.0,4.0,2,...,3.0,5,1,3,2,3,4,3,3,4316715

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
Open_Date = LabelEncoder()
data['Open_Date'] = Open_Date.fit_transform(data['Open_Date'])

City = LabelEncoder()
data['City'] = City.fit_transform(data['City'])

City_Group = LabelEncoder()
data['City_Group'] =City_Group.fit_transform(data['City_Group'])

Type = LabelEncoder()
data['Type'] = Type.fit_transform(data['Type'])

data.head()

,Id,Open_Date,City,City_Group,Type,P1,P2,P3,P4,P5,...,P29,P30,P31,P32,P33,P34,P35,P36,P37,revenue
0,0,101,31,1,2,4,5.0,4.0,4.0,2,...,3.0,5,3,4,5,5,4,3,4,5653753
1,1,56,3,0,1,4,5.0,4.0,4.0,1,...,3.0,0,0,0,0,0,0,0,0,6923131
2,2,73,10,2,2,2,4.0,2.0,5.0,2,...,3.0,0,0,0,0,0,0,0,0,2055379
3,3,57,28,2,2,6,4.5,6.0,6.0,4,...,7.5,25,12,10,6,18,12,12,6,2675511
4,4,88,14,2,2,3,4.0,3.0,4.0,2,...,3.0,5,1,3,2,3,4,3,3,4316715

In [6]:
x=data.drop(['Id','Open_Date','revenue'],axis=1)
y=data['revenue']
x.head()

,City,City_Group,Type,P1,P2,P3,P4,P5,P6,P7,...,P28,P29,P30,P31,P32,P33,P34,P35,P36,P37
0,31,1,2,4,5.0,4.0,4.0,2,2,5,...,2.0,3.0,5,3,4,5,5,4,3,4
1,3,0,1,4,5.0,4.0,4.0,1,2,5,...,3.0,3.0,0,0,0,0,0,0,0,0
2,10,2,2,2,4.0,2.0,5.0,2,3,5,...,1.0,3.0,0,0,0,0,0,0,0,0
3,28,2,2,6,4.5,6.0,6.0,4,4,10,...,2.5,7.5,25,12,10,6,18,12,12,6
4,14,2,2,3,4.0,3.0,4.0,2,2,5,...,1.0,3.0,5,1,3,2,3,4,3,3

In [7]:
data.isnull().sum()

Id            0
Open_Date     0
City          0
City_Group    0
Type          0
P1            0
P2            0
P3            0
P4            0
P5            0
P6            0
P7            0
P8            0
P9            0
P10           0
P11           0
P12           0
P13           0
P14           0
P15           0
P16           0
P17           0
P18           0
P19           0
P20           0
P21           0
P22           0
P23           0
P24           0
P25           0
P26           0
P27           0
P28           0
P29           0
P30           0
P31           0
P32           0
P33           0
P34           0
P35           0
P36           0
P37           0
revenue       0
dtype: int64

## Tree Regressor

In [8]:
from sklearn import tree

In [9]:
rtree=tree.DecisionTreeRegressor()

In [10]:
rtree.fit(x,y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [11]:
feature_imp=pd.DataFrame()
feature_imp['col']=x.columns
feature_imp['imp']=rtree.feature_importances_*100

feature_imp.sort_values('imp',ascending=False)

           col        imp
31         P29  18.592782
0         City  18.193563
17         P15   9.736928
24         P22   9.583971
10          P8   5.282217
5           P3   4.544024
27         P25   4.453664
22         P20   4.270719
30         P28   4.107856
23         P21   3.706793
11          P9   2.800131
3           P1   2.694071
8           P6   2.685498
4           P2   1.782624
12         P10   1.353999
21         P19   1.067079
6           P4   0.989208
20         P18   0.579563
29         P27   0.567876
13         P11   0.552836
18         P16   0.518657
25         P23   0.489601
37         P35   0.359167
16         P14   0.228879
7           P5   0.192840
26         P24   0.142773
14         P12   0.132962
38         P36   0.107886
2         Type   0.068703
9           P7   0.051685
33         P31   0.049162
19         P17   0.038384
1   City_Group   0.038281
15         P13   0.021779
39         P37   0.005440
32         P30   0.004540
34         P32   0.003858
28         P26   0.000000
35         P33   0.000000
36         P34   0.000000

In [12]:
x=x.drop(['P18','P33','P32','P30','P13','P7','P36','P24','P35','City_Group','P31','Type','P12','P17','P14','P5','P27','P34','P11','P37','P16','P10'],axis=1)
x.head()

,City,P1,P2,P3,P4,P6,P8,P9,P15,P19,P20,P21,P22,P23,P25,P26,P28,P29
0,31,4,5.0,4.0,4.0,2,4,5,2,5,4,1,3,3,1,1.0,2.0,3.0
1,3,4,5.0,4.0,4.0,2,5,5,0,3,2,1,3,2,0,0.0,3.0,3.0
2,10,2,4.0,2.0,5.0,3,5,5,0,1,1,1,1,1,0,0.0,1.0,3.0
3,28,6,4.5,6.0,6.0,4,8,10,4,20,12,6,1,10,2,2.5,2.5,7.5
4,14,3,4.0,3.0,4.0,2,5,5,1,2,2,1,2,1,3,3.0,1.0,3.0

In [13]:
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn import metrics
from sklearn import tree
import numpy as np

In [14]:
rtree_model=rtree.fit(x, y)
y_pred=rtree.predict(x)
rtree

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [15]:
y_train_pred= rtree_model.predict(x)
print(np.sqrt(metrics.mean_squared_error(y,y_train_pred)))

859982.2383735374

In [16]:
y.mean()

4453532.613138686

In [17]:
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=.4)

In [74]:
import numpy as np
rtree.fit(x_train, y_train)
y_test_pred=rtree.predict(x_test)
rtree

np.sqrt(metrics.mean_squared_error(y_test,y_test_pred))

3036397.1102985926

In [75]:
comp_df=x_test.copy()
comp_df['actual_value']=y_test
comp_df['predicted_value']=y_test_pred
comp_df.head()

,City,P1,P2,P3,P4,P6,P8,P9,P15,P19,P20,P21,P22,P23,P25,P26,P28,P29,actual_value,predicted_value
96,10,4,5.0,2.0,4.0,2,4,4,0,3,2,1,2,3,0,0.0,2.0,2.0,6412623,2738052.0
124,3,1,3.0,0.0,5.0,5,5,5,0,1,2,2,1,2,0,0.0,2.0,3.0,3810007,3778621.0
26,3,3,5.0,4.0,5.0,3,3,5,4,5,5,2,3,2,2,2.0,3.0,3.0,2267425,3028267.0
22,18,9,6.0,6.0,6.0,6,10,10,0,15,12,3,3,10,0,0.0,7.5,7.5,3956086,3745135.0
70,31,4,5.0,4.0,4.0,4,5,5,0,3,5,1,4,2,0,0.0,3.0,3.0,3982767,4807746.0

In [76]:
comp_df['predicted_value']=comp_df['predicted_value'].astype(np.int64)

In [77]:
comp_df.head()

,City,P1,P2,P3,P4,P6,P8,P9,P15,P19,P20,P21,P22,P23,P25,P26,P28,P29,actual_value,predicted_value
96,10,4,5.0,2.0,4.0,2,4,4,0,3,2,1,2,3,0,0.0,2.0,2.0,6412623,2738052
124,3,1,3.0,0.0,5.0,5,5,5,0,1,2,2,1,2,0,0.0,2.0,3.0,3810007,3778621
26,3,3,5.0,4.0,5.0,3,3,5,4,5,5,2,3,2,2,2.0,3.0,3.0,2267425,3028267
22,18,9,6.0,6.0,6.0,6,10,10,0,15,12,3,3,10,0,0.0,7.5,7.5,3956086,3745135
70,31,4,5.0,4.0,4.0,4,5,5,0,3,5,1,4,2,0,0.0,3.0,3.0,3982767,4807746

In [78]:
y_null=np.zeros_like(y_test)
y_null.fill(y_test.mean())
y_null[1:10]

array([4359366, 4359366, 4359366, 4359366, 4359366, 4359366, 4359366,
       4359366, 4359366], dtype=int64)

In [79]:
np.sqrt(metrics.mean_squared_error(y_test,y_null))

2900366.137992101

In [80]:
param_grid= {"criterion"          : ['mse', 'mae'],
             "max_features"       : [11,12,13,14,15],
             "splitter"           : ['best', 'random'],
             "min_samples_leaf"  : [5,6,7,8,9,10,11,12,13],
             "max_depth"          : [9,10,11,12,13,14]
            }

In [81]:
optimized_tree=GridSearchCV(rtree, param_grid, scoring='neg_mean_absolute_error', cv=5)

In [82]:
optimized_tree.fit(x_train,y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'criterion': ['mse', 'mae'], 'max_features': [11, 12, 13, 14, 15], 'splitter': ['best', 'random'], 'min_samples_leaf': [5, 6, 7, 8, 9, 10, 11, 12, 13], 'max_depth': [9, 10, 11, 12, 13, 14]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='neg_mean_absolute_error', verbose=0)

In [83]:
import sklearn
sklearn.metrics.SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'accuracy', 'roc_auc', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'brier_score_loss', 'adjusted_rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted'])

In [84]:
optimized_tree.best_params_

{'criterion': 'mse',
 'max_depth': 12,
 'max_features': 14,
 'min_samples_leaf': 11,
 'splitter': 'random'}

In [85]:
optimized_tree.best_estimator_

DecisionTreeRegressor(criterion='mse', max_depth=12, max_features=14,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=11,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='random')

In [86]:
optimized_tree.best_score_

-1504709.187815975

In [87]:
rtree_final=optimized_tree.best_estimator_
rtree_final

DecisionTreeRegressor(criterion='mse', max_depth=12, max_features=14,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=11,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='random')

In [89]:
y_test_predict=rtree_final.predict(x_test)
print(np.sqrt(metrics.mean_squared_error(y_test,y_test_predict)))

2756692.4432001924

## Random Forest

In [33]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=1000, oob_score = 'TRUE',n_jobs = -1,random_state =50 ) 
rf.fit(x, y)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=-1,
           oob_score='TRUE', random_state=50, verbose=0, warm_start=False)

In [39]:
comp = pd.DataFrame()
comp['Columns'] = x.columns
comp['Importance'] = rf.feature_importances_*100
comp.sort_values('Importance', inplace=True, ascending=False)
comp

   Columns  Importance
17     P29   20.980461
0     City   15.381623
5       P6    7.865101
16     P28    6.716842
13     P23    6.116626
12     P22    5.599888
10     P20    5.502342
9      P19    4.801040
1       P1    4.096781
6       P8    4.080913
8      P15    3.186705
14     P25    3.007840
11     P21    2.408048
4       P4    2.350490
3       P3    2.215788
15     P26    1.989315
2       P2    1.979175
7       P9    1.721021

In [41]:
x.drop(['P3','P26','P2','P9'],axis=1)
x.head()

,City,P1,P2,P3,P4,P6,P8,P9,P15,P19,P20,P21,P22,P23,P25,P26,P28,P29
0,31,4,5.0,4.0,4.0,2,4,5,2,5,4,1,3,3,1,1.0,2.0,3.0
1,3,4,5.0,4.0,4.0,2,5,5,0,3,2,1,3,2,0,0.0,3.0,3.0
2,10,2,4.0,2.0,5.0,3,5,5,0,1,1,1,1,1,0,0.0,1.0,3.0
3,28,6,4.5,6.0,6.0,4,8,10,4,20,12,6,1,10,2,2.5,2.5,7.5
4,14,3,4.0,3.0,4.0,2,5,5,1,2,2,1,2,1,3,3.0,1.0,3.0

In [60]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=.3)
print(x_train.shape, y_train.shape)

(95, 18) (95,)

In [61]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=1000, oob_score = 'TRUE',n_jobs = -1,random_state =50 ) 
rf.fit(x_train, y_train)
y_test_pred = rf.predict(x_test)
print(np.sqrt(metrics.mean_squared_error(y_test,y_test_pred)))

2845636.754318976

In [62]:
param_grid = { 'n_estimators':[100,500,1000],
              'oob_score': ['TRUE','FALSE'],
              'n_jobs':  [-1,1],
              'random_state': [5,10,40,50]}

In [63]:
optimized_forest = GridSearchCV(rf,param_grid,scoring= 'neg_mean_absolute_error',verbose = 2, cv=5)

In [64]:
optimized_forest.fit(x_train,y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits
[CV] n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=5 .....

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

[CV]  n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=5, total=   7.7s
[CV] n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=5 .....

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    7.8s remaining:    0.0s

[CV]  n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=5, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=5 .....
[CV]  n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=5, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=5 .....
[CV]  n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=5, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=5 .....
[CV]  n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=5, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=10 ....
[CV]  n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=10, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=10 ....
[CV]  n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=10, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=10 ....
[CV]  n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=10, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=10 ....
[CV]  n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=10, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=10 ....
[CV]  n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=10, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=40 ....
[CV]  n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=40, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=40 ....
[CV]  n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=40, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=40 ....
[CV]  n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=40, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=40 ....
[CV]  n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=40, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=40 ....
[CV]  n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=40, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=50 ....
[CV]  n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=50, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=50 ....
[CV]  n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=50, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=50 ....
[CV]  n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=50, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=50 ....
[CV]  n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=50, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=50 ....
[CV]  n_estimators=100, n_jobs=-1, oob_score=TRUE, random_state=50, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=5 ....
[CV]  n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=5, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=5 ....
[CV]  n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=5, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=5 ....
[CV]  n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=5, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=5 ....
[CV]  n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=5, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=5 ....
[CV]  n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=5, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=10 ...
[CV]  n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=10, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=10 ...
[CV]  n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=10, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=10 ...
[CV]  n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=10, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=10 ...
[CV]  n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=10, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=10 ...
[CV]  n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=10, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=40 ...
[CV]  n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=40, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=40 ...
[CV]  n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=40, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=40 ...
[CV]  n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=40, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=40 ...
[CV]  n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=40, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=40 ...
[CV]  n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=40, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=50 ...
[CV]  n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=50, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=50 ...
[CV]  n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=50, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=50 ...
[CV]  n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=50, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=50 ...
[CV]  n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=50, total=   0.2s
[CV] n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=50 ...
[CV]  n_estimators=100, n_jobs=-1, oob_score=FALSE, random_state=50, total=   0.2s
[CV] n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=5 ......
[CV]  n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=5, total=   0.1s
[CV] n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=5 ......
[CV]  n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=5, total=   0.1s
[CV] n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=5 ......
[CV]  n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=5, total=   0.1s
[CV] n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=5 ......
[CV]  n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=5, total=   0.1s
[CV] n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=5 ......
[CV]  n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=5, total=   0.1s
[CV] n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=10 .....
[CV]  n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=10, total=   0.1s
[CV] n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=10 .....
[CV]  n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=10, total=   0.1s
[CV] n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=10 .....
[CV]  n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=10, total=   0.1s
[CV] n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=10 .....
[CV]  n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=10, total=   0.1s
[CV] n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=10 .....
[CV]  n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=10, total=   0.1s
[CV] n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=40 .....
[CV]  n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=40, total=   0.1s
[CV] n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=40 .....
[CV]  n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=40, total=   0.1s
[CV] n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=40 .....
[CV]  n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=40, total=   0.1s
[CV] n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=40 .....
[CV]  n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=40, total=   0.1s
[CV] n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=40 .....
[CV]  n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=40, total=   0.1s
[CV] n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=50 .....

[CV]  n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=50, total=   0.1s
[CV] n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=50 .....
[CV]  n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=50, total=   0.0s
[CV] n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=50 .....
[CV]  n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=50, total=   0.1s
[CV] n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=50 .....
[CV]  n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=50, total=   0.0s
[CV] n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=50 .....
[CV]  n_estimators=100, n_jobs=1, oob_score=TRUE, random_state=50, total=   0.0s
[CV] n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=5 .....
[CV]  n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=5, total=   0.0s
[CV] n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=5 .....
[CV]  n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=5, total=   0.1s
[CV] n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=5 .....
[CV]  n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=5, total=   0.0s
[CV] n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=5 .....
[CV]  n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=5, total=   0.1s
[CV] n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=5 .....
[CV]  n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=5, total=   0.0s
[CV] n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=10 ....
[CV]  n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=10, total=   0.0s
[CV] n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=10 ....
[CV]  n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=10, total=   0.0s
[CV] n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=10 ....
[CV]  n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=10, total=   0.1s
[CV] n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=10 ....
[CV]  n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=10, total=   0.0s
[CV] n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=10 ....
[CV]  n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=10, total=   0.1s
[CV] n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=40 ....
[CV]  n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=40, total=   0.0s
[CV] n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=40 ....
[CV]  n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=40, total=   0.1s
[CV] n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=40 ....
[CV]  n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=40, total=   0.0s
[CV] n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=40 ....
[CV]  n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=40, total=   0.0s
[CV] n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=40 ....
[CV]  n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=40, total=   0.0s
[CV] n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=50 ....
[CV]  n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=50, total=   0.0s
[CV] n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=50 ....
[CV]  n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=50, total=   0.0s
[CV] n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=50 ....
[CV]  n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=50, total=   0.0s
[CV] n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=50 ....
[CV]  n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=50, total=   0.0s
[CV] n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=50 ....
[CV]  n_estimators=100, n_jobs=1, oob_score=FALSE, random_state=50, total=   0.0s
[CV] n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=5 .....
[CV]  n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=5, total=   0.8s
[CV] n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=5 .....
[CV]  n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=5, total=   1.6s
[CV] n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=5 .....
[CV]  n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=5, total=   1.6s
[CV] n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=5 .....
[CV]  n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=5, total=   1.3s
[CV] n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=5 .....
[CV]  n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=5, total=   0.8s
[CV] n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=10 ....
[CV]  n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=10, total=   0.8s
[CV] n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=10 ....
[CV]  n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=10, total=   0.8s
[CV] n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=10 ....
[CV]  n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=10, total=   0.8s
[CV] n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=10 ....
[CV]  n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=10, total=   2.4s
[CV] n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=10 ....
[CV]  n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=10, total=   2.3s
[CV] n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=40 ....
[CV]  n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=40, total=   0.8s
[CV] n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=40 ....
[CV]  n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=40, total=   0.8s
[CV] n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=40 ....
[CV]  n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=40, total=   0.8s
[CV] n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=40 ....
[CV]  n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=40, total=   0.8s
[CV] n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=40 ....
[CV]  n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=40, total=   1.7s
[CV] n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=50 ....
[CV]  n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=50, total=   1.9s
[CV] n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=50 ....
[CV]  n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=50, total=   1.3s
[CV] n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=50 ....
[CV]  n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=50, total=   0.8s
[CV] n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=50 ....
[CV]  n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=50, total=   0.8s
[CV] n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=50 ....
[CV]  n_estimators=500, n_jobs=-1, oob_score=TRUE, random_state=50, total=   0.8s
[CV] n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=5 ....
[CV]  n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=5, total=   0.9s
[CV] n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=5 ....
[CV]  n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=5, total=   1.6s
[CV] n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=5 ....
[CV]  n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=5, total=   1.6s
[CV] n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=5 ....
[CV]  n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=5, total=   1.1s
[CV] n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=5 ....
[CV]  n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=5, total=   0.8s
[CV] n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=10 ...
[CV]  n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=10, total=   0.8s
[CV] n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=10 ...
[CV]  n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=10, total=   0.8s
[CV] n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=10 ...
[CV]  n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=10, total=   1.0s
[CV] n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=10 ...
[CV]  n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=10, total=   3.8s
[CV] n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=10 ...

[CV]  n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=10, total=   0.8s
[CV] n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=40 ...
[CV]  n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=40, total=   0.8s
[CV] n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=40 ...
[CV]  n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=40, total=   0.8s
[CV] n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=40 ...
[CV]  n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=40, total=   1.1s
[CV] n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=40 ...
[CV]  n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=40, total=   5.6s
[CV] n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=40 ...
[CV]  n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=40, total=   1.1s
[CV] n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=50 ...
[CV]  n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=50, total=   1.0s
[CV] n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=50 ...
[CV]  n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=50, total=   1.1s
[CV] n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=50 ...
[CV]  n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=50, total=   1.2s
[CV] n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=50 ...
[CV]  n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=50, total=   1.1s
[CV] n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=50 ...
[CV]  n_estimators=500, n_jobs=-1, oob_score=FALSE, random_state=50, total=   1.1s
[CV] n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=5 ......
[CV]  n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=5, total=   0.8s
[CV] n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=5 ......
[CV]  n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=5, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=5 ......
[CV]  n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=5, total=   0.7s
[CV] n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=5 ......
[CV]  n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=5, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=5 ......
[CV]  n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=5, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=10 .....
[CV]  n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=10, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=10 .....
[CV]  n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=10, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=10 .....
[CV]  n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=10, total=   1.8s
[CV] n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=10 .....
[CV]  n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=10, total=   2.2s
[CV] n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=10 .....
[CV]  n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=10, total=   1.0s
[CV] n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=40 .....
[CV]  n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=40, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=40 .....
[CV]  n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=40, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=40 .....
[CV]  n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=40, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=40 .....
[CV]  n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=40, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=40 .....
[CV]  n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=40, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=50 .....
[CV]  n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=50, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=50 .....
[CV]  n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=50, total=   4.7s
[CV] n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=50 .....
[CV]  n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=50, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=50 .....
[CV]  n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=50, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=50 .....
[CV]  n_estimators=500, n_jobs=1, oob_score=TRUE, random_state=50, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=5 .....
[CV]  n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=5, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=5 .....
[CV]  n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=5, total=   0.7s
[CV] n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=5 .....
[CV]  n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=5, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=5 .....
[CV]  n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=5, total=   1.9s
[CV] n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=5 .....
[CV]  n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=5, total=   2.7s
[CV] n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=10 ....
[CV]  n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=10, total=   0.7s
[CV] n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=10 ....
[CV]  n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=10, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=10 ....
[CV]  n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=10, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=10 ....
[CV]  n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=10, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=10 ....
[CV]  n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=10, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=40 ....
[CV]  n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=40, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=40 ....
[CV]  n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=40, total=   1.1s
[CV] n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=40 ....
[CV]  n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=40, total=   2.7s
[CV] n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=40 ....
[CV]  n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=40, total=   1.4s
[CV] n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=40 ....
[CV]  n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=40, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=50 ....
[CV]  n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=50, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=50 ....
[CV]  n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=50, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=50 ....
[CV]  n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=50, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=50 ....
[CV]  n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=50, total=   0.6s
[CV] n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=50 ....
[CV]  n_estimators=500, n_jobs=1, oob_score=FALSE, random_state=50, total=   0.6s
[CV] n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=5 ....
[CV]  n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=5, total=   5.4s
[CV] n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=5 ....
[CV]  n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=5, total=   1.6s
[CV] n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=5 ....
[CV]  n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=5, total=   1.6s
[CV] n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=5 ....

[CV]  n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=5, total=   3.9s
[CV] n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=5 ....
[CV]  n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=5, total=   1.8s
[CV] n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=10 ...
[CV]  n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=10, total=   1.6s
[CV] n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=10 ...
[CV]  n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=10, total=   2.4s
[CV] n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=10 ...
[CV]  n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=10, total=   3.9s
[CV] n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=10 ...
[CV]  n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=10, total=   1.5s
[CV] n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=10 ...
[CV]  n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=10, total=   1.7s
[CV] n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=40 ...
[CV]  n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=40, total=   4.8s
[CV] n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=40 ...
[CV]  n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=40, total=   1.6s
[CV] n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=40 ...
[CV]  n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=40, total=   1.7s
[CV] n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=40 ...
[CV]  n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=40, total=   5.7s
[CV] n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=40 ...
[CV]  n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=40, total=   1.9s
[CV] n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=50 ...
[CV]  n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=50, total=   1.9s
[CV] n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=50 ...
[CV]  n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=50, total=   2.1s
[CV] n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=50 ...
[CV]  n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=50, total=   1.7s
[CV] n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=50 ...
[CV]  n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=50, total=   1.6s
[CV] n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=50 ...
[CV]  n_estimators=1000, n_jobs=-1, oob_score=TRUE, random_state=50, total=   1.5s
[CV] n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=5 ...
[CV]  n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=5, total=   4.6s
[CV] n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=5 ...
[CV]  n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=5, total=   1.6s
[CV] n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=5 ...
[CV]  n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=5, total=   1.7s
[CV] n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=5 ...
[CV]  n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=5, total=   5.7s
[CV] n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=5 ...
[CV]  n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=5, total=   1.6s
[CV] n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=10 ..
[CV]  n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=10, total=   1.6s
[CV] n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=10 ..
[CV]  n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=10, total=   5.4s
[CV] n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=10 ..
[CV]  n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=10, total=   1.7s
[CV] n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=10 ..
[CV]  n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=10, total=   1.5s
[CV] n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=10 ..
[CV]  n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=10, total=   2.3s
[CV] n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=40 ..
[CV]  n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=40, total=   2.3s
[CV] n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=40 ..
[CV]  n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=40, total=   1.5s
[CV] n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=40 ..
[CV]  n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=40, total=   1.6s
[CV] n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=40 ..
[CV]  n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=40, total=   2.2s
[CV] n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=40 ..
[CV]  n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=40, total=   2.7s
[CV] n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=50 ..
[CV]  n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=50, total=   1.6s
[CV] n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=50 ..
[CV]  n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=50, total=   1.6s
[CV] n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=50 ..
[CV]  n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=50, total=   1.5s
[CV] n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=50 ..
[CV]  n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=50, total=   2.0s
[CV] n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=50 ..
[CV]  n_estimators=1000, n_jobs=-1, oob_score=FALSE, random_state=50, total=   2.0s
[CV] n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=5 .....
[CV]  n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=5, total=   1.6s
[CV] n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=5 .....
[CV]  n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=5, total=   1.6s
[CV] n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=5 .....
[CV]  n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=5, total=   1.6s
[CV] n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=5 .....
[CV]  n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=5, total=   1.4s
[CV] n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=5 .....
[CV]  n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=5, total=   1.3s
[CV] n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=10 ....
[CV]  n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=10, total=   1.3s
[CV] n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=10 ....
[CV]  n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=10, total=   5.3s
[CV] n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=10 ....
[CV]  n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=10, total=   1.3s
[CV] n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=10 ....
[CV]  n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=10, total=   1.3s
[CV] n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=10 ....
[CV]  n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=10, total=   1.3s
[CV] n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=40 ....
[CV]  n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=40, total=   2.4s
[CV] n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=40 ....
[CV]  n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=40, total=   2.8s
[CV] n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=40 ....
[CV]  n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=40, total=   1.3s
[CV] n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=40 ....
[CV]  n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=40, total=   1.3s
[CV] n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=40 ....
[CV]  n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=40, total=   1.3s
[CV] n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=50 ....
[CV]  n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=50, total=   2.1s
[CV] n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=50 ....
[CV]  n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=50, total=   2.1s
[CV] n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=50 ....

[CV]  n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=50, total=   1.4s
[CV] n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=50 ....
[CV]  n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=50, total=   1.3s
[CV] n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=50 ....
[CV]  n_estimators=1000, n_jobs=1, oob_score=TRUE, random_state=50, total=   1.4s
[CV] n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=5 ....
[CV]  n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=5, total=   2.9s
[CV] n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=5 ....
[CV]  n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=5, total=   3.0s
[CV] n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=5 ....
[CV]  n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=5, total=   1.3s
[CV] n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=5 ....
[CV]  n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=5, total=   1.3s
[CV] n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=5 ....
[CV]  n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=5, total=   1.5s
[CV] n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=10 ...
[CV]  n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=10, total=   4.2s
[CV] n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=10 ...
[CV]  n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=10, total=   1.3s
[CV] n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=10 ...
[CV]  n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=10, total=   1.4s
[CV] n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=10 ...
[CV]  n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=10, total=   1.3s
[CV] n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=10 ...
[CV]  n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=10, total=   5.1s
[CV] n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=40 ...
[CV]  n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=40, total=   1.3s
[CV] n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=40 ...
[CV]  n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=40, total=   1.3s
[CV] n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=40 ...
[CV]  n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=40, total=   1.3s
[CV] n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=40 ...
[CV]  n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=40, total=   1.7s
[CV] n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=40 ...
[CV]  n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=40, total=   1.8s
[CV] n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=50 ...
[CV]  n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=50, total=   1.8s
[CV] n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=50 ...
[CV]  n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=50, total=   1.3s
[CV] n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=50 ...
[CV]  n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=50, total=   1.3s
[CV] n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=50 ...
[CV]  n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=50, total=   1.3s
[CV] n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=50 ...
[CV]  n_estimators=1000, n_jobs=1, oob_score=FALSE, random_state=50, total=   4.9s

[Parallel(n_jobs=1)]: Done 240 out of 240 | elapsed:  5.7min finished

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=-1,
           oob_score='TRUE', random_state=50, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_estimators': [100, 500, 1000], 'oob_score': ['TRUE', 'FALSE'], 'n_jobs': [-1, 1], 'random_state': [5, 10, 40, 50]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='neg_mean_absolute_error', verbose=2)

In [65]:
optimized_forest.best_score_

-1760788.1001784462

In [66]:
optimized_forest.best_params_

{'n_estimators': 500, 'n_jobs': -1, 'oob_score': 'TRUE', 'random_state': 40}

In [67]:
optimized_forest.best_estimator_

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=-1,
           oob_score='TRUE', random_state=40, verbose=0, warm_start=False)

In [68]:
optimized_forest.best_index_

18

In [69]:
final_model = optimized_forest.best_estimator_

In [70]:
y_test_pred1 = final_model.predict(x_test)

In [71]:
c = x_test.copy()
c['Actual'] = y_test
c['Prediction'] = y_test_pred1
c.head()

,City,P1,P2,P3,P4,P6,P8,P9,P15,P19,P20,P21,P22,P23,P25,P26,P28,P29,Actual,Prediction
96,10,4,5.0,2.0,4.0,2,4,4,0,3,2,1,2,3,0,0.0,2.0,2.0,6412623,4.483914e+06
124,3,1,3.0,0.0,5.0,5,5,5,0,1,2,2,1,2,0,0.0,2.0,3.0,3810007,4.471521e+06
26,3,3,5.0,4.0,5.0,3,3,5,4,5,5,2,3,2,2,2.0,3.0,3.0,2267425,3.781883e+06
22,18,9,6.0,6.0,6.0,6,10,10,0,15,12,3,3,10,0,0.0,7.5,7.5,3956086,4.098496e+06
70,31,4,5.0,4.0,4.0,4,5,5,0,3,5,1,4,2,0,0.0,3.0,3.0,3982767,4.564167e+06

In [73]:
print(np.sqrt(metrics.mean_squared_error(y_test,y_test_pred1)))

2848723.4675284424